import openai
import os

# Once you add your API key below, make sure to not share it with anyone! The API key should remain private.
openai.api_key = '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'


# Open the file in read mode
file_path = 'ai.txt'  # Replace with the actual path or filename
with open(file_path, 'r') as file:
    # Read the lines and store them into a list
    file_content = file.readlines()
# Display the content of the list
print(file_content)

# Join the list of lines into a single string
input_text = ''.join(file_content)

# Format the input text as a list of messages for OpenAI's Chat API
messages = [{"role": "system", "content": "Did you generate these lines?"},
            {"role": "user", "content": input_text}]

# Make a request to OpenAI's Chat API
completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=messages
)

# Get the generated response from the API
generated_response = completion['choices'][0]['message']['content']

# Print or use the generated response as needed
print("Generated Response:")
print(generated_response)



if ('Yes' or 'yes') in generated_response:
	print("This document is being likely being generated by ChatGPT")
if ('No' or 'no') in generated_response:
	print("This document is likely not bing generated by ChatGPT")
	
