
import openai
from PIL import Image
openai.api_key = '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'
try:
    import pytesseract
    pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
    def extract_text_from_image(image_path):
        with Image.open(image_path) as img:
            text_content = pytesseract.image_to_string(img)
        return text_content

    # Replace 'your_image.png' with the actual path or filename of your image
    image_path = 'Okay.png'
    extracted_text = extract_text_from_image(image_path)


    # Display the extracted text
    print(extracted_text)
    cleaned_text = ' '.join(extracted_text.split())  # Remove extra whitespaces and line breaks

        # Limit the text to the first 100 words
    words = cleaned_text.split()[:100]
    limited_text = ' '.join(words)

    messages = [{"role": "system", "content": "Did you generate these lines? Yes or no?"},
                {"role": "user", "content": limited_text}]

    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages
    )

    generated_response = completion['choices'][0]['message']['content']


    print("Generated Response:")
    print(generated_response)

    if 'Yes' in generated_response or 'yes' in generated_response:
        print("This document is likely being generated by ChatGPT")
        

    if 'No' in generated_response or 'no' in generated_response:
        print("This document is likely not being generated by ChatGPT")
except TesseractNotFoundError:
    print("Tesseract missing form sytem")
except:
    print("Error!")
