import pdfplumber
import openai
import os

# Once you add your API key below, make sure to not share it with anyone! The API key should remain private.
openai.api_key = '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'

def extract_and_trim_text_from_pdf(pdf_path):
    with pdfplumber.open(pdf_path) as pdf:
        text_content = ""
        for page in pdf.pages:
            text_content += page.extract_text()

    # Clean up the extracted text
    cleaned_text = ' '.join(text_content.split())  # Remove extra whitespaces and line breaks

    # Limit the text to the first 100 words
    words = cleaned_text.split()[:100]
    limited_text = ' '.join(words)

    return limited_text


pdf_path = 'test.pdf'
limited_text = extract_and_trim_text_from_pdf(pdf_path)

# Display the limited text with exactly 100 words
print(limited_text)


messages = [{"role": "system", "content": "Did you generate these lines?"},
            {"role": "user", "content": limited_text}]

completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=messages
)

generated_response = completion['choices'][0]['message']['content']


print("Generated Response:")
print(generated_response)

if 'Yes' in generated_response or 'yes' in generated_response:
    print("This document is likely being generated by ChatGPT")
    

if 'No' in generated_response or 'no' in generated_response:
    print("This document is likely not being generated by ChatGPT")

